    # projeto_raiz/docker-compose.yml
    version: '3.8'

    services:
      fastapi_app:
        build:
          context: .
          dockerfile: deploy_lstm/Dockerfile
        container_name: lstm_api_container_compose
        restart: unless-stopped
        ports:
          - "8000:8000"
        volumes:
          - ./modelo/melhor_modelo_lstm.keras:/app/melhor_modelo_lstm.keras
          - ./modelo/min_max_scaler.gz:/app/min_max_scaler.gz
        networks:
          - monitor_net

      prometheus:
        image: prom/prometheus:v2.50.1
        container_name: prometheus_server
        restart: unless-stopped
        ports:
          - "9090:9090"
        volumes:
          - ./deploy_lstm/prometheus.yml:/etc/prometheus/prometheus.yml
          # - prometheus_data:/prometheus # Descomente para persistir dados do Prometheus
        command:
          - '--config.file=/etc/prometheus/prometheus.yml'
          - '--storage.tsdb.path=/prometheus'
          - '--web.console.libraries=/usr/share/prometheus/console_libraries'
          - '--web.console.templates=/usr/share/prometheus/consoles'
          - '--web.enable-lifecycle'
        networks:
          - monitor_net

      grafana:
        image: grafana/grafana-oss:10.4.2
        container_name: grafana_dashboard
        restart: unless-stopped
        ports:
          - "3000:3000"
        volumes:
          - grafana_data:/var/lib/grafana # Persiste dados do Grafana como plugins, configurações de utilizador, etc.
          # Montar os diretórios de provisioning:
          - ./grafana_provisioning/datasources:/etc/grafana/provisioning/datasources
          - ./grafana_provisioning/dashboards:/etc/grafana/provisioning/dashboards
        environment:
          - GF_SECURITY_ADMIN_USER=admin
          - GF_SECURITY_ADMIN_PASSWORD=grafana # Mude isto!
          # GF_USERS_ALLOW_SIGN_UP=false
        depends_on:
          - prometheus
        networks:
          - monitor_net

    networks:
      monitor_net:
        driver: bridge

    volumes:
      # prometheus_data:
      grafana_data:
    