{
 "title": "API LSTM TC4",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Métricas de Previsões", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "QTD. Falha no carregamento do modelo",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 1, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "api_modelo_carregado_falha_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QTD. Sucesso no Carregamento do Modelo",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "api_modelo_carregado_sucesso_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total de Previsões",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "api_previsoes_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Taxa de Previsões (por minuto)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "rate(api_previsoes_total[1m]) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latência Média de Previsão (5m avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(api_tempo_processamento_previsao_seconds_sum[5m]) / rate(api_tempo_processamento_previsao_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latência de Previsão p95 (5m avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 9, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(api_tempo_processamento_previsao_seconds_bucket[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Métricas /prever/", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Taxa de Requisições /prever/ (por segundo)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(starlette_requests_total{method=\"POST\", path=\"/prever/\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Tempo Médio de Resposta /prever (POST)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 9, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(starlette_request_duration_seconds_sum{path=\"/prever/\", method=\"POST\"}[5m])) by (path) / sum(rate(starlette_request_duration_seconds_count{path=\"/prever/\", method=\"POST\"}[5m])) by (path)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Métricas HTTP Totais", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Taxa de Requisições (por segundo)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(starlette_requests_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Tempo Médio de Resposta HTTP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 9, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(path) (rate(starlette_request_duration_seconds_sum[5m])) / sum by(path) (rate(starlette_request_duration_seconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "taxa de erros 5xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(starlette_requests_total{status_code=~\"5..\"}[1m])) by (path) / sum(rate(starlette_requests_total[1m])) by (path) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "taxa de erros 4xx (Cliente)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 9, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(starlette_requests_total{status_code=~\"4..\"}[1m])) by (path) / sum(rate(starlette_requests_total[1m])) by (path) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}